### ISSUE TITLE
deps: remove wheel from PEP518 default dependencies

### ISSUE THREAD

**Issue by stanislavlevin** [stanislavlevin/pyproject_installer#87]
According to updated `PEP518` specification (https://packaging.python.org/en/latest/specifications/pyproject-toml/#declaring-build-system-dependencies-the-build-system-table):

> An example [build-system] table for a project built with setuptools is:
 ```toml
  [build-system]
  # Minimum requirements for the build system to execute.
  requires = ["setuptools"]
  ```
> Build tools are expected to use the example configuration file above as their default semantics when a pyproject.toml file is not present.

`wheel` is (was) `PEP517` `setuptools`' dependency.
